#pragma once

enum e_field_types : int {
	field_void = 0,
	field_float,
	field_string,
	field_vector,
	field_quaternion,
	field_integer,
	field_boolean,
	field_short,
	field_character,
	field_color32,
	field_embedded,
	field_custom,
	field_classptr,
	field_ehandle,
	field_edict,
	field_position_vector,
	field_time,
	field_tick,
	field_modelname,
	field_soundname,
	field_input,
	field_function,
	field_vmatrix,
	field_vmatrix_worldspace,
	field_matrix3x4_worldspace,
	field_interval,
	field_modelindex,
	field_materialindex,
	field_vector2d,
	field_integer64,
	field_vector4d,
	field_typecount
};
